from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.bridge_interface_ifpathcost import BridgeInterfaceIfpathcost
    from ..models.bridge_interface_ifpriority import BridgeInterfaceIfpriority


T = TypeVar("T", bound="BridgeInterface")


@_attrs_define
class BridgeInterface:
    """
    Attributes:
        members (list[str]):
        enablestp (bool | Unset): enable RSTP/STP
        descr (str | Unset): description
        maxaddr (int | Unset): cache size of the bridge address, default is 2000 entries
        timeout (int | Unset): cache expire time, default is 1200 seconds
        maxage (int | Unset): the time that a Spanning Tree Protocol configuration is valid
            default is 20 seconds, minimum is 6 seconds and maximum is 40 seconds
        fwdelay (int | Unset): the time that must pass before an interface begins forwarding packets when spanning tree
            is enabled
            default is 15 seconds, minimum is 4 seconds and maximum is 30 seconds
        hellotime (int | Unset): the time in seconds between broadcasting of STP configuration messages
            default is 2 seconds, minimum is 1 second and maximum is 2 seconds
        priority (int | Unset): the bridge priority for spanning tree
            default is 32768, minimum is 0 and maximum is 61440
        proto (str | Unset): protocol used for spanning tree
            valid value = "rstp" or "stp"
        holdcnt (int | Unset): the transmit hold count for spanning tree
            default is 6, minimum is 1 and maximum is 10
        ip6linklocal (bool | Unset): enable IPv6 auto linklocal
        ifpriority (BridgeInterfaceIfpriority | Unset):
        ifpathcost (BridgeInterfaceIfpathcost | Unset):
        static (list[str] | Unset):
        private (list[str] | Unset):
        stp (list[str] | Unset):
        span (list[str] | Unset):
        edge (list[str] | Unset):
        autoedge (list[str] | Unset):
        ptp (list[str] | Unset):
        autoptp (list[str] | Unset):
        bridgeif_device (str | Unset): generated by system when a Bridge is created
    """

    members: list[str]
    enablestp: bool | Unset = UNSET
    descr: str | Unset = UNSET
    maxaddr: int | Unset = UNSET
    timeout: int | Unset = UNSET
    maxage: int | Unset = UNSET
    fwdelay: int | Unset = UNSET
    hellotime: int | Unset = UNSET
    priority: int | Unset = UNSET
    proto: str | Unset = UNSET
    holdcnt: int | Unset = UNSET
    ip6linklocal: bool | Unset = UNSET
    ifpriority: BridgeInterfaceIfpriority | Unset = UNSET
    ifpathcost: BridgeInterfaceIfpathcost | Unset = UNSET
    static: list[str] | Unset = UNSET
    private: list[str] | Unset = UNSET
    stp: list[str] | Unset = UNSET
    span: list[str] | Unset = UNSET
    edge: list[str] | Unset = UNSET
    autoedge: list[str] | Unset = UNSET
    ptp: list[str] | Unset = UNSET
    autoptp: list[str] | Unset = UNSET
    bridgeif_device: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        members = self.members

        enablestp = self.enablestp

        descr = self.descr

        maxaddr = self.maxaddr

        timeout = self.timeout

        maxage = self.maxage

        fwdelay = self.fwdelay

        hellotime = self.hellotime

        priority = self.priority

        proto = self.proto

        holdcnt = self.holdcnt

        ip6linklocal = self.ip6linklocal

        ifpriority: dict[str, Any] | Unset = UNSET
        if not isinstance(self.ifpriority, Unset):
            ifpriority = self.ifpriority.to_dict()

        ifpathcost: dict[str, Any] | Unset = UNSET
        if not isinstance(self.ifpathcost, Unset):
            ifpathcost = self.ifpathcost.to_dict()

        static: list[str] | Unset = UNSET
        if not isinstance(self.static, Unset):
            static = self.static

        private: list[str] | Unset = UNSET
        if not isinstance(self.private, Unset):
            private = self.private

        stp: list[str] | Unset = UNSET
        if not isinstance(self.stp, Unset):
            stp = self.stp

        span: list[str] | Unset = UNSET
        if not isinstance(self.span, Unset):
            span = self.span

        edge: list[str] | Unset = UNSET
        if not isinstance(self.edge, Unset):
            edge = self.edge

        autoedge: list[str] | Unset = UNSET
        if not isinstance(self.autoedge, Unset):
            autoedge = self.autoedge

        ptp: list[str] | Unset = UNSET
        if not isinstance(self.ptp, Unset):
            ptp = self.ptp

        autoptp: list[str] | Unset = UNSET
        if not isinstance(self.autoptp, Unset):
            autoptp = self.autoptp

        bridgeif_device = self.bridgeif_device

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "members": members,
            }
        )
        if enablestp is not UNSET:
            field_dict["enablestp"] = enablestp
        if descr is not UNSET:
            field_dict["descr"] = descr
        if maxaddr is not UNSET:
            field_dict["maxaddr"] = maxaddr
        if timeout is not UNSET:
            field_dict["timeout"] = timeout
        if maxage is not UNSET:
            field_dict["maxage"] = maxage
        if fwdelay is not UNSET:
            field_dict["fwdelay"] = fwdelay
        if hellotime is not UNSET:
            field_dict["hellotime"] = hellotime
        if priority is not UNSET:
            field_dict["priority"] = priority
        if proto is not UNSET:
            field_dict["proto"] = proto
        if holdcnt is not UNSET:
            field_dict["holdcnt"] = holdcnt
        if ip6linklocal is not UNSET:
            field_dict["ip6linklocal"] = ip6linklocal
        if ifpriority is not UNSET:
            field_dict["ifpriority"] = ifpriority
        if ifpathcost is not UNSET:
            field_dict["ifpathcost"] = ifpathcost
        if static is not UNSET:
            field_dict["static"] = static
        if private is not UNSET:
            field_dict["private"] = private
        if stp is not UNSET:
            field_dict["stp"] = stp
        if span is not UNSET:
            field_dict["span"] = span
        if edge is not UNSET:
            field_dict["edge"] = edge
        if autoedge is not UNSET:
            field_dict["autoedge"] = autoedge
        if ptp is not UNSET:
            field_dict["ptp"] = ptp
        if autoptp is not UNSET:
            field_dict["autoptp"] = autoptp
        if bridgeif_device is not UNSET:
            field_dict["bridgeif_device"] = bridgeif_device

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.bridge_interface_ifpathcost import BridgeInterfaceIfpathcost
        from ..models.bridge_interface_ifpriority import BridgeInterfaceIfpriority

        d = dict(src_dict)
        members = cast(list[str], d.pop("members"))

        enablestp = d.pop("enablestp", UNSET)

        descr = d.pop("descr", UNSET)

        maxaddr = d.pop("maxaddr", UNSET)

        timeout = d.pop("timeout", UNSET)

        maxage = d.pop("maxage", UNSET)

        fwdelay = d.pop("fwdelay", UNSET)

        hellotime = d.pop("hellotime", UNSET)

        priority = d.pop("priority", UNSET)

        proto = d.pop("proto", UNSET)

        holdcnt = d.pop("holdcnt", UNSET)

        ip6linklocal = d.pop("ip6linklocal", UNSET)

        _ifpriority = d.pop("ifpriority", UNSET)
        ifpriority: BridgeInterfaceIfpriority | Unset
        if isinstance(_ifpriority, Unset):
            ifpriority = UNSET
        else:
            ifpriority = BridgeInterfaceIfpriority.from_dict(_ifpriority)

        _ifpathcost = d.pop("ifpathcost", UNSET)
        ifpathcost: BridgeInterfaceIfpathcost | Unset
        if isinstance(_ifpathcost, Unset):
            ifpathcost = UNSET
        else:
            ifpathcost = BridgeInterfaceIfpathcost.from_dict(_ifpathcost)

        static = cast(list[str], d.pop("static", UNSET))

        private = cast(list[str], d.pop("private", UNSET))

        stp = cast(list[str], d.pop("stp", UNSET))

        span = cast(list[str], d.pop("span", UNSET))

        edge = cast(list[str], d.pop("edge", UNSET))

        autoedge = cast(list[str], d.pop("autoedge", UNSET))

        ptp = cast(list[str], d.pop("ptp", UNSET))

        autoptp = cast(list[str], d.pop("autoptp", UNSET))

        bridgeif_device = d.pop("bridgeif_device", UNSET)

        bridge_interface = cls(
            members=members,
            enablestp=enablestp,
            descr=descr,
            maxaddr=maxaddr,
            timeout=timeout,
            maxage=maxage,
            fwdelay=fwdelay,
            hellotime=hellotime,
            priority=priority,
            proto=proto,
            holdcnt=holdcnt,
            ip6linklocal=ip6linklocal,
            ifpriority=ifpriority,
            ifpathcost=ifpathcost,
            static=static,
            private=private,
            stp=stp,
            span=span,
            edge=edge,
            autoedge=autoedge,
            ptp=ptp,
            autoptp=autoptp,
            bridgeif_device=bridgeif_device,
        )

        bridge_interface.additional_properties = d
        return bridge_interface

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
