from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.lagg_interface_lacptimeout import LAGGInterfaceLacptimeout
from ..models.lagg_interface_proto import LAGGInterfaceProto
from ..types import UNSET, Unset

T = TypeVar("T", bound="LAGGInterface")


@_attrs_define
class LAGGInterface:
    """
    Attributes:
        members (list[str]):
        descr (str | Unset): description
        laggif_device (str | Unset): generated by system when create lagg
        proto (LAGGInterfaceProto | Unset): lagg protocol
            valid value = none, lacp, failover, loadbalance, roundrobin
        failovermaster (str | Unset): (for proto=failover only) failover master interface
        lacptimeout (LAGGInterfaceLacptimeout | Unset): (for proto=lacp only) LACP Timeout Mode
            valid value = slow, fast
        lagghash (str | Unset): (for proto=lacp or loadbalance) hash algorithms for the packet layers
            valid value = "l2,l3,l4", "l2", "l3", "l4", "l2,l3", "l3,l4", "l2,l4"
    """

    members: list[str]
    descr: str | Unset = UNSET
    laggif_device: str | Unset = UNSET
    proto: LAGGInterfaceProto | Unset = UNSET
    failovermaster: str | Unset = UNSET
    lacptimeout: LAGGInterfaceLacptimeout | Unset = UNSET
    lagghash: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        members = self.members

        descr = self.descr

        laggif_device = self.laggif_device

        proto: str | Unset = UNSET
        if not isinstance(self.proto, Unset):
            proto = self.proto.value

        failovermaster = self.failovermaster

        lacptimeout: str | Unset = UNSET
        if not isinstance(self.lacptimeout, Unset):
            lacptimeout = self.lacptimeout.value

        lagghash = self.lagghash

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "members": members,
            }
        )
        if descr is not UNSET:
            field_dict["descr"] = descr
        if laggif_device is not UNSET:
            field_dict["laggif_device"] = laggif_device
        if proto is not UNSET:
            field_dict["proto"] = proto
        if failovermaster is not UNSET:
            field_dict["failovermaster"] = failovermaster
        if lacptimeout is not UNSET:
            field_dict["lacptimeout"] = lacptimeout
        if lagghash is not UNSET:
            field_dict["lagghash"] = lagghash

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        members = cast(list[str], d.pop("members"))

        descr = d.pop("descr", UNSET)

        laggif_device = d.pop("laggif_device", UNSET)

        _proto = d.pop("proto", UNSET)
        proto: LAGGInterfaceProto | Unset
        if isinstance(_proto, Unset):
            proto = UNSET
        else:
            proto = LAGGInterfaceProto(_proto)

        failovermaster = d.pop("failovermaster", UNSET)

        _lacptimeout = d.pop("lacptimeout", UNSET)
        lacptimeout: LAGGInterfaceLacptimeout | Unset
        if isinstance(_lacptimeout, Unset):
            lacptimeout = UNSET
        else:
            lacptimeout = LAGGInterfaceLacptimeout(_lacptimeout)

        lagghash = d.pop("lagghash", UNSET)

        lagg_interface = cls(
            members=members,
            descr=descr,
            laggif_device=laggif_device,
            proto=proto,
            failovermaster=failovermaster,
            lacptimeout=lacptimeout,
            lagghash=lagghash,
        )

        lagg_interface.additional_properties = d
        return lagg_interface

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
