from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.limiter_queue_aqm import LimiterQueueAqm
from ..models.limiter_queue_mask import LimiterQueueMask
from ..types import UNSET, Unset

T = TypeVar("T", bound="LimiterQueue")


@_attrs_define
class LimiterQueue:
    """
    Attributes:
        name (str): name of the limiter, it will appear for selection on firewall rules
        enabled (bool | Unset):
        number (int | Unset): generated by system when create limiter queue
        mask (LimiterQueueMask | Unset): controls how the limiter will mask addresses in the queue
            valid values = none, srcaddress, dstaddress
        maskbits (int | Unset): address masking for ipv4
        maskbitsv6 (int | Unset): address masking for ipv6
        description (str | Unset):
        aqm (LimiterQueueAqm | Unset): active queue management (AQM) algorithm
            valid values = droptail, codel, pie, red, gred
        param_codel_target (str | Unset): (for aqm=codel only) codel target delay in ms (set to "" to use default value)
        param_codel_interval (str | Unset): (for aqm=codel only) codel interval in ms (set to "" to use default value)
        param_pie_target (str | Unset): (for aqm=pie only) target delay in ms (set to "" to use default value)
        param_pie_tupdate (str | Unset): (for aqm=pie only) interval in ms (set to "" to use default value)
        param_pie_alpha (str | Unset): (for aqm=pie only) alpha (set to "" to use default value)
        param_pie_beta (str | Unset): (for aqm=pie only) beta (set to "" to use default value)
        param_pie_max_burst (str | Unset): (for aqm=pie only) max burst (set to "" to use default value)
        param_pie_max_ecnth (str | Unset): (for aqm=pie only) max ecnth (set to "" to use default value)
        param_red_w_q (str | Unset): (for aqm=red only) w_q (set to "" to use default value)
        param_red_min_th (str | Unset): (for aqm=red only) min_th (set to "" to use default value)
        param_red_max_th (str | Unset): (for aqm=red only) max_th (set to "" to use default value)
        param_red_max_p (str | Unset): (for aqm=red only) max_p (set to "" to use default value)
        param_gred_w_q (str | Unset): (for aqm=gred only) w_q (set to "" to use default value)
        param_gred_min_th (str | Unset): (for aqm=gred only) min_th (set to "" to use default value)
        param_gred_max_th (str | Unset): (for aqm=gred only) max_th (set to "" to use default value)
        param_gred_max_p (str | Unset): (for aqm=gred only) max_p (set to "" to use default value)
        ecn (bool | Unset): (for aqm=codel, pie, red, or gred only) explicit congestion notification
        pie_onoff (bool | Unset): (for aqm=pie only) turning pie on and off depending on queue load
        pie_capdrop (bool | Unset): (for aqm=pie only) cap drop adjustment
        pie_qdelay (bool | Unset): (for aqm=pie only) set queue delay type to timestamps (true) or departure rate
            estimation (false)
        pie_pderand (bool | Unset): (for aqm=pie only) drop probability de-randomisation
        qlimit (int | Unset): specifies the length of this queue, which the AQM is responsible for
        weight (int | Unset): this value can range from 1 to 100, higher values give more precedence to packets in a
            given queue
        plr (float | Unset): packet loss rate can be configured to drop a certain fraction of packets that enter the
            limiter
            valid value between 0 and 1
            a value of 0.001 means one packet in 1000 gets dropped
        buckets (int | Unset): bucket Size, specified in slots, sets the size of the hash table used for queue storage
    """

    name: str
    enabled: bool | Unset = UNSET
    number: int | Unset = UNSET
    mask: LimiterQueueMask | Unset = UNSET
    maskbits: int | Unset = UNSET
    maskbitsv6: int | Unset = UNSET
    description: str | Unset = UNSET
    aqm: LimiterQueueAqm | Unset = UNSET
    param_codel_target: str | Unset = UNSET
    param_codel_interval: str | Unset = UNSET
    param_pie_target: str | Unset = UNSET
    param_pie_tupdate: str | Unset = UNSET
    param_pie_alpha: str | Unset = UNSET
    param_pie_beta: str | Unset = UNSET
    param_pie_max_burst: str | Unset = UNSET
    param_pie_max_ecnth: str | Unset = UNSET
    param_red_w_q: str | Unset = UNSET
    param_red_min_th: str | Unset = UNSET
    param_red_max_th: str | Unset = UNSET
    param_red_max_p: str | Unset = UNSET
    param_gred_w_q: str | Unset = UNSET
    param_gred_min_th: str | Unset = UNSET
    param_gred_max_th: str | Unset = UNSET
    param_gred_max_p: str | Unset = UNSET
    ecn: bool | Unset = UNSET
    pie_onoff: bool | Unset = UNSET
    pie_capdrop: bool | Unset = UNSET
    pie_qdelay: bool | Unset = UNSET
    pie_pderand: bool | Unset = UNSET
    qlimit: int | Unset = UNSET
    weight: int | Unset = UNSET
    plr: float | Unset = UNSET
    buckets: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        enabled = self.enabled

        number = self.number

        mask: str | Unset = UNSET
        if not isinstance(self.mask, Unset):
            mask = self.mask.value

        maskbits = self.maskbits

        maskbitsv6 = self.maskbitsv6

        description = self.description

        aqm: str | Unset = UNSET
        if not isinstance(self.aqm, Unset):
            aqm = self.aqm.value

        param_codel_target = self.param_codel_target

        param_codel_interval = self.param_codel_interval

        param_pie_target = self.param_pie_target

        param_pie_tupdate = self.param_pie_tupdate

        param_pie_alpha = self.param_pie_alpha

        param_pie_beta = self.param_pie_beta

        param_pie_max_burst = self.param_pie_max_burst

        param_pie_max_ecnth = self.param_pie_max_ecnth

        param_red_w_q = self.param_red_w_q

        param_red_min_th = self.param_red_min_th

        param_red_max_th = self.param_red_max_th

        param_red_max_p = self.param_red_max_p

        param_gred_w_q = self.param_gred_w_q

        param_gred_min_th = self.param_gred_min_th

        param_gred_max_th = self.param_gred_max_th

        param_gred_max_p = self.param_gred_max_p

        ecn = self.ecn

        pie_onoff = self.pie_onoff

        pie_capdrop = self.pie_capdrop

        pie_qdelay = self.pie_qdelay

        pie_pderand = self.pie_pderand

        qlimit = self.qlimit

        weight = self.weight

        plr = self.plr

        buckets = self.buckets

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "name": name,
            }
        )
        if enabled is not UNSET:
            field_dict["enabled"] = enabled
        if number is not UNSET:
            field_dict["number"] = number
        if mask is not UNSET:
            field_dict["mask"] = mask
        if maskbits is not UNSET:
            field_dict["maskbits"] = maskbits
        if maskbitsv6 is not UNSET:
            field_dict["maskbitsv6"] = maskbitsv6
        if description is not UNSET:
            field_dict["description"] = description
        if aqm is not UNSET:
            field_dict["aqm"] = aqm
        if param_codel_target is not UNSET:
            field_dict["param_codel_target"] = param_codel_target
        if param_codel_interval is not UNSET:
            field_dict["param_codel_interval"] = param_codel_interval
        if param_pie_target is not UNSET:
            field_dict["param_pie_target"] = param_pie_target
        if param_pie_tupdate is not UNSET:
            field_dict["param_pie_tupdate"] = param_pie_tupdate
        if param_pie_alpha is not UNSET:
            field_dict["param_pie_alpha"] = param_pie_alpha
        if param_pie_beta is not UNSET:
            field_dict["param_pie_beta"] = param_pie_beta
        if param_pie_max_burst is not UNSET:
            field_dict["param_pie_max_burst"] = param_pie_max_burst
        if param_pie_max_ecnth is not UNSET:
            field_dict["param_pie_max_ecnth"] = param_pie_max_ecnth
        if param_red_w_q is not UNSET:
            field_dict["param_red_w_q"] = param_red_w_q
        if param_red_min_th is not UNSET:
            field_dict["param_red_min_th"] = param_red_min_th
        if param_red_max_th is not UNSET:
            field_dict["param_red_max_th"] = param_red_max_th
        if param_red_max_p is not UNSET:
            field_dict["param_red_max_p"] = param_red_max_p
        if param_gred_w_q is not UNSET:
            field_dict["param_gred_w_q"] = param_gred_w_q
        if param_gred_min_th is not UNSET:
            field_dict["param_gred_min_th"] = param_gred_min_th
        if param_gred_max_th is not UNSET:
            field_dict["param_gred_max_th"] = param_gred_max_th
        if param_gred_max_p is not UNSET:
            field_dict["param_gred_max_p"] = param_gred_max_p
        if ecn is not UNSET:
            field_dict["ecn"] = ecn
        if pie_onoff is not UNSET:
            field_dict["pie_onoff"] = pie_onoff
        if pie_capdrop is not UNSET:
            field_dict["pie_capdrop"] = pie_capdrop
        if pie_qdelay is not UNSET:
            field_dict["pie_qdelay"] = pie_qdelay
        if pie_pderand is not UNSET:
            field_dict["pie_pderand"] = pie_pderand
        if qlimit is not UNSET:
            field_dict["qlimit"] = qlimit
        if weight is not UNSET:
            field_dict["weight"] = weight
        if plr is not UNSET:
            field_dict["plr"] = plr
        if buckets is not UNSET:
            field_dict["buckets"] = buckets

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("name")

        enabled = d.pop("enabled", UNSET)

        number = d.pop("number", UNSET)

        _mask = d.pop("mask", UNSET)
        mask: LimiterQueueMask | Unset
        if isinstance(_mask, Unset):
            mask = UNSET
        else:
            mask = LimiterQueueMask(_mask)

        maskbits = d.pop("maskbits", UNSET)

        maskbitsv6 = d.pop("maskbitsv6", UNSET)

        description = d.pop("description", UNSET)

        _aqm = d.pop("aqm", UNSET)
        aqm: LimiterQueueAqm | Unset
        if isinstance(_aqm, Unset):
            aqm = UNSET
        else:
            aqm = LimiterQueueAqm(_aqm)

        param_codel_target = d.pop("param_codel_target", UNSET)

        param_codel_interval = d.pop("param_codel_interval", UNSET)

        param_pie_target = d.pop("param_pie_target", UNSET)

        param_pie_tupdate = d.pop("param_pie_tupdate", UNSET)

        param_pie_alpha = d.pop("param_pie_alpha", UNSET)

        param_pie_beta = d.pop("param_pie_beta", UNSET)

        param_pie_max_burst = d.pop("param_pie_max_burst", UNSET)

        param_pie_max_ecnth = d.pop("param_pie_max_ecnth", UNSET)

        param_red_w_q = d.pop("param_red_w_q", UNSET)

        param_red_min_th = d.pop("param_red_min_th", UNSET)

        param_red_max_th = d.pop("param_red_max_th", UNSET)

        param_red_max_p = d.pop("param_red_max_p", UNSET)

        param_gred_w_q = d.pop("param_gred_w_q", UNSET)

        param_gred_min_th = d.pop("param_gred_min_th", UNSET)

        param_gred_max_th = d.pop("param_gred_max_th", UNSET)

        param_gred_max_p = d.pop("param_gred_max_p", UNSET)

        ecn = d.pop("ecn", UNSET)

        pie_onoff = d.pop("pie_onoff", UNSET)

        pie_capdrop = d.pop("pie_capdrop", UNSET)

        pie_qdelay = d.pop("pie_qdelay", UNSET)

        pie_pderand = d.pop("pie_pderand", UNSET)

        qlimit = d.pop("qlimit", UNSET)

        weight = d.pop("weight", UNSET)

        plr = d.pop("plr", UNSET)

        buckets = d.pop("buckets", UNSET)

        limiter_queue = cls(
            name=name,
            enabled=enabled,
            number=number,
            mask=mask,
            maskbits=maskbits,
            maskbitsv6=maskbitsv6,
            description=description,
            aqm=aqm,
            param_codel_target=param_codel_target,
            param_codel_interval=param_codel_interval,
            param_pie_target=param_pie_target,
            param_pie_tupdate=param_pie_tupdate,
            param_pie_alpha=param_pie_alpha,
            param_pie_beta=param_pie_beta,
            param_pie_max_burst=param_pie_max_burst,
            param_pie_max_ecnth=param_pie_max_ecnth,
            param_red_w_q=param_red_w_q,
            param_red_min_th=param_red_min_th,
            param_red_max_th=param_red_max_th,
            param_red_max_p=param_red_max_p,
            param_gred_w_q=param_gred_w_q,
            param_gred_min_th=param_gred_min_th,
            param_gred_max_th=param_gred_max_th,
            param_gred_max_p=param_gred_max_p,
            ecn=ecn,
            pie_onoff=pie_onoff,
            pie_capdrop=pie_capdrop,
            pie_qdelay=pie_qdelay,
            pie_pderand=pie_pderand,
            qlimit=qlimit,
            weight=weight,
            plr=plr,
            buckets=buckets,
        )

        limiter_queue.additional_properties = d
        return limiter_queue

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
