from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="OpenVPNClientConfig")


@_attrs_define
class OpenVPNClientConfig:
    """
    Attributes:
        vpnid (str | Unset): generated by system when create openvpn server
        disable (bool | Unset):
        dco (bool | Unset):
        protocol (str | Unset):
        dev_mode (str | Unset):
        interface (str | Unset):
        ipaddr (str | Unset):
        local_port (int | Unset):
        server_addr (str | Unset):
        server_port (str | Unset):
        proxy_addr (str | Unset):
        proxy_port (str | Unset):
        proxy_authtype (str | Unset):
        description (str | Unset):
        mode (str | Unset):
        topology (str | Unset):
        custom_options (str | Unset):
        caref (str | Unset):
        certref (str | Unset):
        crlref (str | Unset):
        tlsauth_enable (bool | Unset):
        autokey_enable (bool | Unset):
        autotls_enable (bool | Unset):
        tls (str | Unset): OpenVPN TLS key
        tls_type (str | Unset): "auth" or "crypt"
        tlsauth_keydir (str | Unset):
        remote_cert_tls (bool | Unset):
        shared_key (str | Unset):
        digest (str | Unset):
        tunnel_network (str | Unset):
        tunnel_networkv6 (str | Unset):
        remote_network (str | Unset):
        remote_networkv6 (str | Unset):
        use_shaper (str | Unset):
        allow_compression (str | Unset): "asym", "yes", "no"
        compression (str | Unset):
        auth_retry_none (bool | Unset):
        passtos (bool | Unset):
        udp_fast_io (bool | Unset):
        exit_notify (str | Unset):
        sndrcvbuf (str | Unset):
        route_no_pull (bool | Unset):
        route_no_exec (bool | Unset):
        dns_add (bool | Unset):
        verbosity_level (str | Unset):
        create_gw (str | Unset):
        dh_length (str | Unset):
        data_ciphers (list[str] | Unset):
        data_ciphers_fallback (str | Unset):
        ping_method (str | Unset):
        keepalive_interval (str | Unset):
        keepalive_timeout (str | Unset):
        ping_seconds (str | Unset):
        ping_action (str | Unset):
        ping_action_seconds (str | Unset):
        inactive_seconds (str | Unset):
    """

    vpnid: str | Unset = UNSET
    disable: bool | Unset = UNSET
    dco: bool | Unset = UNSET
    protocol: str | Unset = UNSET
    dev_mode: str | Unset = UNSET
    interface: str | Unset = UNSET
    ipaddr: str | Unset = UNSET
    local_port: int | Unset = UNSET
    server_addr: str | Unset = UNSET
    server_port: str | Unset = UNSET
    proxy_addr: str | Unset = UNSET
    proxy_port: str | Unset = UNSET
    proxy_authtype: str | Unset = UNSET
    description: str | Unset = UNSET
    mode: str | Unset = UNSET
    topology: str | Unset = UNSET
    custom_options: str | Unset = UNSET
    caref: str | Unset = UNSET
    certref: str | Unset = UNSET
    crlref: str | Unset = UNSET
    tlsauth_enable: bool | Unset = UNSET
    autokey_enable: bool | Unset = UNSET
    autotls_enable: bool | Unset = UNSET
    tls: str | Unset = UNSET
    tls_type: str | Unset = UNSET
    tlsauth_keydir: str | Unset = UNSET
    remote_cert_tls: bool | Unset = UNSET
    shared_key: str | Unset = UNSET
    digest: str | Unset = UNSET
    tunnel_network: str | Unset = UNSET
    tunnel_networkv6: str | Unset = UNSET
    remote_network: str | Unset = UNSET
    remote_networkv6: str | Unset = UNSET
    use_shaper: str | Unset = UNSET
    allow_compression: str | Unset = UNSET
    compression: str | Unset = UNSET
    auth_retry_none: bool | Unset = UNSET
    passtos: bool | Unset = UNSET
    udp_fast_io: bool | Unset = UNSET
    exit_notify: str | Unset = UNSET
    sndrcvbuf: str | Unset = UNSET
    route_no_pull: bool | Unset = UNSET
    route_no_exec: bool | Unset = UNSET
    dns_add: bool | Unset = UNSET
    verbosity_level: str | Unset = UNSET
    create_gw: str | Unset = UNSET
    dh_length: str | Unset = UNSET
    data_ciphers: list[str] | Unset = UNSET
    data_ciphers_fallback: str | Unset = UNSET
    ping_method: str | Unset = UNSET
    keepalive_interval: str | Unset = UNSET
    keepalive_timeout: str | Unset = UNSET
    ping_seconds: str | Unset = UNSET
    ping_action: str | Unset = UNSET
    ping_action_seconds: str | Unset = UNSET
    inactive_seconds: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        vpnid = self.vpnid

        disable = self.disable

        dco = self.dco

        protocol = self.protocol

        dev_mode = self.dev_mode

        interface = self.interface

        ipaddr = self.ipaddr

        local_port = self.local_port

        server_addr = self.server_addr

        server_port = self.server_port

        proxy_addr = self.proxy_addr

        proxy_port = self.proxy_port

        proxy_authtype = self.proxy_authtype

        description = self.description

        mode = self.mode

        topology = self.topology

        custom_options = self.custom_options

        caref = self.caref

        certref = self.certref

        crlref = self.crlref

        tlsauth_enable = self.tlsauth_enable

        autokey_enable = self.autokey_enable

        autotls_enable = self.autotls_enable

        tls = self.tls

        tls_type = self.tls_type

        tlsauth_keydir = self.tlsauth_keydir

        remote_cert_tls = self.remote_cert_tls

        shared_key = self.shared_key

        digest = self.digest

        tunnel_network = self.tunnel_network

        tunnel_networkv6 = self.tunnel_networkv6

        remote_network = self.remote_network

        remote_networkv6 = self.remote_networkv6

        use_shaper = self.use_shaper

        allow_compression = self.allow_compression

        compression = self.compression

        auth_retry_none = self.auth_retry_none

        passtos = self.passtos

        udp_fast_io = self.udp_fast_io

        exit_notify = self.exit_notify

        sndrcvbuf = self.sndrcvbuf

        route_no_pull = self.route_no_pull

        route_no_exec = self.route_no_exec

        dns_add = self.dns_add

        verbosity_level = self.verbosity_level

        create_gw = self.create_gw

        dh_length = self.dh_length

        data_ciphers: list[str] | Unset = UNSET
        if not isinstance(self.data_ciphers, Unset):
            data_ciphers = self.data_ciphers

        data_ciphers_fallback = self.data_ciphers_fallback

        ping_method = self.ping_method

        keepalive_interval = self.keepalive_interval

        keepalive_timeout = self.keepalive_timeout

        ping_seconds = self.ping_seconds

        ping_action = self.ping_action

        ping_action_seconds = self.ping_action_seconds

        inactive_seconds = self.inactive_seconds

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if vpnid is not UNSET:
            field_dict["vpnid"] = vpnid
        if disable is not UNSET:
            field_dict["disable"] = disable
        if dco is not UNSET:
            field_dict["dco"] = dco
        if protocol is not UNSET:
            field_dict["protocol"] = protocol
        if dev_mode is not UNSET:
            field_dict["dev_mode"] = dev_mode
        if interface is not UNSET:
            field_dict["interface"] = interface
        if ipaddr is not UNSET:
            field_dict["ipaddr"] = ipaddr
        if local_port is not UNSET:
            field_dict["local_port"] = local_port
        if server_addr is not UNSET:
            field_dict["server_addr"] = server_addr
        if server_port is not UNSET:
            field_dict["server_port"] = server_port
        if proxy_addr is not UNSET:
            field_dict["proxy_addr"] = proxy_addr
        if proxy_port is not UNSET:
            field_dict["proxy_port"] = proxy_port
        if proxy_authtype is not UNSET:
            field_dict["proxy_authtype"] = proxy_authtype
        if description is not UNSET:
            field_dict["description"] = description
        if mode is not UNSET:
            field_dict["mode"] = mode
        if topology is not UNSET:
            field_dict["topology"] = topology
        if custom_options is not UNSET:
            field_dict["custom_options"] = custom_options
        if caref is not UNSET:
            field_dict["caref"] = caref
        if certref is not UNSET:
            field_dict["certref"] = certref
        if crlref is not UNSET:
            field_dict["crlref"] = crlref
        if tlsauth_enable is not UNSET:
            field_dict["tlsauth_enable"] = tlsauth_enable
        if autokey_enable is not UNSET:
            field_dict["autokey_enable"] = autokey_enable
        if autotls_enable is not UNSET:
            field_dict["autotls_enable"] = autotls_enable
        if tls is not UNSET:
            field_dict["tls"] = tls
        if tls_type is not UNSET:
            field_dict["tls_type"] = tls_type
        if tlsauth_keydir is not UNSET:
            field_dict["tlsauth_keydir"] = tlsauth_keydir
        if remote_cert_tls is not UNSET:
            field_dict["remote_cert_tls"] = remote_cert_tls
        if shared_key is not UNSET:
            field_dict["shared_key"] = shared_key
        if digest is not UNSET:
            field_dict["digest"] = digest
        if tunnel_network is not UNSET:
            field_dict["tunnel_network"] = tunnel_network
        if tunnel_networkv6 is not UNSET:
            field_dict["tunnel_networkv6"] = tunnel_networkv6
        if remote_network is not UNSET:
            field_dict["remote_network"] = remote_network
        if remote_networkv6 is not UNSET:
            field_dict["remote_networkv6"] = remote_networkv6
        if use_shaper is not UNSET:
            field_dict["use_shaper"] = use_shaper
        if allow_compression is not UNSET:
            field_dict["allow_compression"] = allow_compression
        if compression is not UNSET:
            field_dict["compression"] = compression
        if auth_retry_none is not UNSET:
            field_dict["auth_retry_none"] = auth_retry_none
        if passtos is not UNSET:
            field_dict["passtos"] = passtos
        if udp_fast_io is not UNSET:
            field_dict["udp_fast_io"] = udp_fast_io
        if exit_notify is not UNSET:
            field_dict["exit_notify"] = exit_notify
        if sndrcvbuf is not UNSET:
            field_dict["sndrcvbuf"] = sndrcvbuf
        if route_no_pull is not UNSET:
            field_dict["route_no_pull"] = route_no_pull
        if route_no_exec is not UNSET:
            field_dict["route_no_exec"] = route_no_exec
        if dns_add is not UNSET:
            field_dict["dns_add"] = dns_add
        if verbosity_level is not UNSET:
            field_dict["verbosity_level"] = verbosity_level
        if create_gw is not UNSET:
            field_dict["create_gw"] = create_gw
        if dh_length is not UNSET:
            field_dict["dh_length"] = dh_length
        if data_ciphers is not UNSET:
            field_dict["data_ciphers"] = data_ciphers
        if data_ciphers_fallback is not UNSET:
            field_dict["data_ciphers_fallback"] = data_ciphers_fallback
        if ping_method is not UNSET:
            field_dict["ping_method"] = ping_method
        if keepalive_interval is not UNSET:
            field_dict["keepalive_interval"] = keepalive_interval
        if keepalive_timeout is not UNSET:
            field_dict["keepalive_timeout"] = keepalive_timeout
        if ping_seconds is not UNSET:
            field_dict["ping_seconds"] = ping_seconds
        if ping_action is not UNSET:
            field_dict["ping_action"] = ping_action
        if ping_action_seconds is not UNSET:
            field_dict["ping_action_seconds"] = ping_action_seconds
        if inactive_seconds is not UNSET:
            field_dict["inactive_seconds"] = inactive_seconds

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        vpnid = d.pop("vpnid", UNSET)

        disable = d.pop("disable", UNSET)

        dco = d.pop("dco", UNSET)

        protocol = d.pop("protocol", UNSET)

        dev_mode = d.pop("dev_mode", UNSET)

        interface = d.pop("interface", UNSET)

        ipaddr = d.pop("ipaddr", UNSET)

        local_port = d.pop("local_port", UNSET)

        server_addr = d.pop("server_addr", UNSET)

        server_port = d.pop("server_port", UNSET)

        proxy_addr = d.pop("proxy_addr", UNSET)

        proxy_port = d.pop("proxy_port", UNSET)

        proxy_authtype = d.pop("proxy_authtype", UNSET)

        description = d.pop("description", UNSET)

        mode = d.pop("mode", UNSET)

        topology = d.pop("topology", UNSET)

        custom_options = d.pop("custom_options", UNSET)

        caref = d.pop("caref", UNSET)

        certref = d.pop("certref", UNSET)

        crlref = d.pop("crlref", UNSET)

        tlsauth_enable = d.pop("tlsauth_enable", UNSET)

        autokey_enable = d.pop("autokey_enable", UNSET)

        autotls_enable = d.pop("autotls_enable", UNSET)

        tls = d.pop("tls", UNSET)

        tls_type = d.pop("tls_type", UNSET)

        tlsauth_keydir = d.pop("tlsauth_keydir", UNSET)

        remote_cert_tls = d.pop("remote_cert_tls", UNSET)

        shared_key = d.pop("shared_key", UNSET)

        digest = d.pop("digest", UNSET)

        tunnel_network = d.pop("tunnel_network", UNSET)

        tunnel_networkv6 = d.pop("tunnel_networkv6", UNSET)

        remote_network = d.pop("remote_network", UNSET)

        remote_networkv6 = d.pop("remote_networkv6", UNSET)

        use_shaper = d.pop("use_shaper", UNSET)

        allow_compression = d.pop("allow_compression", UNSET)

        compression = d.pop("compression", UNSET)

        auth_retry_none = d.pop("auth_retry_none", UNSET)

        passtos = d.pop("passtos", UNSET)

        udp_fast_io = d.pop("udp_fast_io", UNSET)

        exit_notify = d.pop("exit_notify", UNSET)

        sndrcvbuf = d.pop("sndrcvbuf", UNSET)

        route_no_pull = d.pop("route_no_pull", UNSET)

        route_no_exec = d.pop("route_no_exec", UNSET)

        dns_add = d.pop("dns_add", UNSET)

        verbosity_level = d.pop("verbosity_level", UNSET)

        create_gw = d.pop("create_gw", UNSET)

        dh_length = d.pop("dh_length", UNSET)

        data_ciphers = cast(list[str], d.pop("data_ciphers", UNSET))

        data_ciphers_fallback = d.pop("data_ciphers_fallback", UNSET)

        ping_method = d.pop("ping_method", UNSET)

        keepalive_interval = d.pop("keepalive_interval", UNSET)

        keepalive_timeout = d.pop("keepalive_timeout", UNSET)

        ping_seconds = d.pop("ping_seconds", UNSET)

        ping_action = d.pop("ping_action", UNSET)

        ping_action_seconds = d.pop("ping_action_seconds", UNSET)

        inactive_seconds = d.pop("inactive_seconds", UNSET)

        open_vpn_client_config = cls(
            vpnid=vpnid,
            disable=disable,
            dco=dco,
            protocol=protocol,
            dev_mode=dev_mode,
            interface=interface,
            ipaddr=ipaddr,
            local_port=local_port,
            server_addr=server_addr,
            server_port=server_port,
            proxy_addr=proxy_addr,
            proxy_port=proxy_port,
            proxy_authtype=proxy_authtype,
            description=description,
            mode=mode,
            topology=topology,
            custom_options=custom_options,
            caref=caref,
            certref=certref,
            crlref=crlref,
            tlsauth_enable=tlsauth_enable,
            autokey_enable=autokey_enable,
            autotls_enable=autotls_enable,
            tls=tls,
            tls_type=tls_type,
            tlsauth_keydir=tlsauth_keydir,
            remote_cert_tls=remote_cert_tls,
            shared_key=shared_key,
            digest=digest,
            tunnel_network=tunnel_network,
            tunnel_networkv6=tunnel_networkv6,
            remote_network=remote_network,
            remote_networkv6=remote_networkv6,
            use_shaper=use_shaper,
            allow_compression=allow_compression,
            compression=compression,
            auth_retry_none=auth_retry_none,
            passtos=passtos,
            udp_fast_io=udp_fast_io,
            exit_notify=exit_notify,
            sndrcvbuf=sndrcvbuf,
            route_no_pull=route_no_pull,
            route_no_exec=route_no_exec,
            dns_add=dns_add,
            verbosity_level=verbosity_level,
            create_gw=create_gw,
            dh_length=dh_length,
            data_ciphers=data_ciphers,
            data_ciphers_fallback=data_ciphers_fallback,
            ping_method=ping_method,
            keepalive_interval=keepalive_interval,
            keepalive_timeout=keepalive_timeout,
            ping_seconds=ping_seconds,
            ping_action=ping_action,
            ping_action_seconds=ping_action_seconds,
            inactive_seconds=inactive_seconds,
        )

        open_vpn_client_config.additional_properties = d
        return open_vpn_client_config

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
