from typing import Any, Dict, List, Type, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="QinQInterface")


@_attrs_define
class QinQInterface:
    """
    Attributes:
        if_device (str): parent interface
        tag (int): first level VLAN tag
        autogroup (bool): adds interface to QinQ interface groups
        members (List[str]):
        descr (str): description
        vlanif (str): generated by system when a QinQ is created
    """

    if_device: str
    tag: int
    autogroup: bool
    members: List[str]
    descr: str
    vlanif: str
    additional_properties: Dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        if_device = self.if_device

        tag = self.tag

        autogroup = self.autogroup

        members = self.members

        descr = self.descr

        vlanif = self.vlanif

        field_dict: Dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "if_device": if_device,
                "tag": tag,
                "autogroup": autogroup,
                "members": members,
                "descr": descr,
                "vlanif": vlanif,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: Type[T], src_dict: Dict[str, Any]) -> T:
        d = src_dict.copy()
        if_device = d.pop("if_device")

        tag = d.pop("tag")

        autogroup = d.pop("autogroup")

        members = cast(List[str], d.pop("members"))

        descr = d.pop("descr")

        vlanif = d.pop("vlanif")

        qin_q_interface = cls(
            if_device=if_device,
            tag=tag,
            autogroup=autogroup,
            members=members,
            descr=descr,
            vlanif=vlanif,
        )

        qin_q_interface.additional_properties = d
        return qin_q_interface

    @property
    def additional_keys(self) -> List[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
