from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="QinQInterface")


@_attrs_define
class QinQInterface:
    """
    Attributes:
        if_device (str): parent interface
        tag (int): first level VLAN tag
        tag_type (str | Unset):
        autogroup (bool | Unset): adds interface to QinQ interface groups
        members (list[str] | Unset):
        descr (str | Unset): description
        vlanif (str | Unset): generated by system when a QinQ is created
    """

    if_device: str
    tag: int
    tag_type: str | Unset = UNSET
    autogroup: bool | Unset = UNSET
    members: list[str] | Unset = UNSET
    descr: str | Unset = UNSET
    vlanif: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        if_device = self.if_device

        tag = self.tag

        tag_type = self.tag_type

        autogroup = self.autogroup

        members: list[str] | Unset = UNSET
        if not isinstance(self.members, Unset):
            members = self.members

        descr = self.descr

        vlanif = self.vlanif

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "if_device": if_device,
                "tag": tag,
            }
        )
        if tag_type is not UNSET:
            field_dict["tag_type"] = tag_type
        if autogroup is not UNSET:
            field_dict["autogroup"] = autogroup
        if members is not UNSET:
            field_dict["members"] = members
        if descr is not UNSET:
            field_dict["descr"] = descr
        if vlanif is not UNSET:
            field_dict["vlanif"] = vlanif

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        if_device = d.pop("if_device")

        tag = d.pop("tag")

        tag_type = d.pop("tag_type", UNSET)

        autogroup = d.pop("autogroup", UNSET)

        members = cast(list[str], d.pop("members", UNSET))

        descr = d.pop("descr", UNSET)

        vlanif = d.pop("vlanif", UNSET)

        qin_q_interface = cls(
            if_device=if_device,
            tag=tag,
            tag_type=tag_type,
            autogroup=autogroup,
            members=members,
            descr=descr,
            vlanif=vlanif,
        )

        qin_q_interface.additional_properties = d
        return qin_q_interface

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
