from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="VLANInterface")


@_attrs_define
class VLANInterface:
    """
    Attributes:
        if_device (str): parent interface of the VLAN
        tag (int | Unset): 802.1Q VLAN tag (between 1 and 4094)
        tag_type (str | Unset): C-tag or S-tag
        pcp (int | Unset): 802.1Q VLAN Priority (between 0 and 7)
        descr (str | Unset): description
        vlanif (str | Unset): generated by system when a VLAN is created
    """

    if_device: str
    tag: int | Unset = UNSET
    tag_type: str | Unset = UNSET
    pcp: int | Unset = UNSET
    descr: str | Unset = UNSET
    vlanif: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        if_device = self.if_device

        tag = self.tag

        tag_type = self.tag_type

        pcp = self.pcp

        descr = self.descr

        vlanif = self.vlanif

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "if_device": if_device,
            }
        )
        if tag is not UNSET:
            field_dict["tag"] = tag
        if tag_type is not UNSET:
            field_dict["tag_type"] = tag_type
        if pcp is not UNSET:
            field_dict["pcp"] = pcp
        if descr is not UNSET:
            field_dict["descr"] = descr
        if vlanif is not UNSET:
            field_dict["vlanif"] = vlanif

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        if_device = d.pop("if_device")

        tag = d.pop("tag", UNSET)

        tag_type = d.pop("tag_type", UNSET)

        pcp = d.pop("pcp", UNSET)

        descr = d.pop("descr", UNSET)

        vlanif = d.pop("vlanif", UNSET)

        vlan_interface = cls(
            if_device=if_device,
            tag=tag,
            tag_type=tag_type,
            pcp=pcp,
            descr=descr,
            vlanif=vlanif,
        )

        vlan_interface.additional_properties = d
        return vlan_interface

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
